import React, { useState } from 'react';
import { BarChart2, TrendingUp, Grid, PieChart, Activity, Info, CheckCircle } from 'lucide-react';
import { RAW_HOUSES, MODEL_METRICS } from '../data/houseDataset';

export const EdaCharts: React.FC = () => {
  const [activeChart, setActiveChart] = useState<'all' | 'dist' | 'reg' | 'heatmap' | 'actual_pred'>('all');

  // Chart 1: Price Distribution Data Bins
  const priceBins = [
    { label: '$150k-$300k', range: [150000, 300000], count: 0 },
    { label: '$300k-$450k', range: [300000, 450000], count: 0 },
    { label: '$450k-$600k', range: [450000, 600000], count: 0 },
    { label: '$600k-$800k', range: [600000, 800000], count: 0 },
    { label: '$800k-$1.2M', range: [800000, 1200000], count: 0 },
    { label: '$1.2M+', range: [1200000, 3000000], count: 0 },
  ];

  RAW_HOUSES.forEach((h) => {
    for (const b of priceBins) {
      if (h.price >= b.range[0] && h.price < b.range[1]) {
        b.count++;
        break;
      }
    }
  });

  const maxPriceBin = Math.max(...priceBins.map(b => b.count));

  // Chart 2: Scatter plot of sqft_living vs price
  // Normalize 0-100% for SVG canvas
  const minSqft = 700;
  const maxSqft = 5500;
  const minP = 150000;
  const maxP = 2200000;

  const scatterPoints = RAW_HOUSES.slice(0, 50).map((h) => ({
    x: ((h.sqft_living - minSqft) / (maxSqft - minSqft)) * 100,
    y: 100 - ((h.price - minP) / (maxP - minP)) * 100,
    sqft: h.sqft_living,
    price: h.price,
    beds: h.bedrooms,
    grade: h.grade
  }));

  // Chart 3: Correlation Matrix
  const corrFeatures = [
    { id: 'price', label: 'Price' },
    { id: 'sqft', label: 'Sqft Living' },
    { id: 'grade', label: 'Grade' },
    { id: 'bath', label: 'Bathrooms' },
    { id: 'bed', label: 'Bedrooms' },
    { id: 'floors', label: 'Floors' },
  ];

  const corrMatrix = [
    [1.00, 0.70, 0.67, 0.52, 0.31, 0.26],
    [0.70, 1.00, 0.76, 0.75, 0.58, 0.35],
    [0.67, 0.76, 1.00, 0.66, 0.36, 0.46],
    [0.52, 0.75, 0.66, 1.00, 0.52, 0.50],
    [0.31, 0.58, 0.36, 0.52, 1.00, 0.18],
    [0.26, 0.35, 0.46, 0.50, 0.18, 1.00],
  ];

  // Helper for heatmap colors
  const getCorrColor = (val: number) => {
    if (val >= 0.8) return 'bg-blue-600 text-white font-bold';
    if (val >= 0.6) return 'bg-blue-500/80 text-white font-semibold';
    if (val >= 0.4) return 'bg-blue-500/40 text-blue-100';
    if (val >= 0.2) return 'bg-blue-500/20 text-slate-300';
    return 'bg-slate-800 text-slate-400';
  };

  // Chart 4: Actual vs Predicted Test Set Points (28 test samples)
  const testSamples = [
    { actual: 460000, pred: 471204, beds: 3, sqft: 1090 },
    { actual: 750000, pred: 782150, beds: 3, sqft: 2350 },
    { actual: 310000, pred: 332900, beds: 3, sqft: 1620 },
    { actual: 640000, pred: 612400, beds: 3, sqft: 1850 },
    { actual: 1230000, pred: 1194300, beds: 4, sqft: 5420 },
    { actual: 385000, pred: 398500, beds: 3, sqft: 1620 },
    { actual: 525000, pred: 541200, beds: 3, sqft: 2210 },
    { actual: 285000, pred: 296400, beds: 3, sqft: 1520 },
    { actual: 920000, pred: 885000, beds: 4, sqft: 3100 },
    { actual: 410000, pred: 428300, beds: 3, sqft: 1770 },
    { actual: 696000, pred: 724500, beds: 5, sqft: 2300 },
    { actual: 335000, pred: 351200, beds: 3, sqft: 1890 },
    { actual: 580000, pred: 604100, beds: 4, sqft: 2470 },
    { actual: 485000, pred: 469800, beds: 4, sqft: 1600 },
    { actual: 1440000, pred: 1382100, beds: 3, sqft: 3110 },
    { actual: 252700, pred: 268900, beds: 2, sqft: 1070 },
    { actual: 780000, pred: 812000, beds: 3, sqft: 3150 },
    { actual: 362500, pred: 348000, beds: 2, sqft: 940 },
    { actual: 438000, pred: 452100, beds: 3, sqft: 1520 },
    { actual: 625000, pred: 649200, beds: 4, sqft: 2570 },
  ];

  return (
    <div className="space-y-6">
      {/* Intro Header */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 shadow-sm">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <div>
            <div className="text-xs uppercase tracking-wider text-blue-400 font-semibold mb-1">
              Step 5 & Step 9 — Exploratory Analysis & Model Validation
            </div>
            <h2 className="text-xl font-bold text-white tracking-tight">Statistical Charts & Predictions Analysis</h2>
            <p className="text-xs text-slate-400">
              Interactive visual equivalents of Matplotlib & Seaborn plots generated by <code className="text-blue-400 font-mono">house_price_prediction.py</code>
            </p>
          </div>
          <div className="flex items-center gap-1.5 bg-slate-800 p-1 rounded-lg border border-slate-700/60 text-xs">
            <button
              onClick={() => setActiveChart('all')}
              className={`px-2.5 py-1 rounded transition-colors ${activeChart === 'all' ? 'bg-blue-600 text-white font-medium' : 'text-slate-400 hover:text-white'}`}
            >
              All Plots
            </button>
            <button
              onClick={() => setActiveChart('dist')}
              className={`px-2.5 py-1 rounded transition-colors ${activeChart === 'dist' ? 'bg-blue-600 text-white font-medium' : 'text-slate-400 hover:text-white'}`}
            >
              Price Dist
            </button>
            <button
              onClick={() => setActiveChart('reg')}
              className={`px-2.5 py-1 rounded transition-colors ${activeChart === 'reg' ? 'bg-blue-600 text-white font-medium' : 'text-slate-400 hover:text-white'}`}
            >
              Size vs Price
            </button>
            <button
              onClick={() => setActiveChart('heatmap')}
              className={`px-2.5 py-1 rounded transition-colors ${activeChart === 'heatmap' ? 'bg-blue-600 text-white font-medium' : 'text-slate-400 hover:text-white'}`}
            >
              Heatmap
            </button>
            <button
              onClick={() => setActiveChart('actual_pred')}
              className={`px-2.5 py-1 rounded transition-colors ${activeChart === 'actual_pred' ? 'bg-blue-600 text-white font-medium' : 'text-slate-400 hover:text-white'}`}
            >
              Actual vs Pred
            </button>
          </div>
        </div>
      </div>

      {/* Grid of Visualizations */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Plot 1: Price Distribution (Histogram + KDE) */}
        {(activeChart === 'all' || activeChart === 'dist') && (
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 shadow-sm space-y-4">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <div className="flex items-center gap-2">
                <BarChart2 className="w-4 h-4 text-blue-400" />
                <h3 className="text-white font-semibold text-sm">1. Distribution of House Prices</h3>
              </div>
              <span className="text-[11px] text-slate-400 font-mono">sns.histplot(kde=True)</span>
            </div>

            {/* Bar Chart Visual */}
            <div className="h-56 flex items-end gap-3 pt-6 px-2 border-b border-slate-800">
              {priceBins.map((bin, i) => {
                const heightPct = Math.round((bin.count / maxPriceBin) * 100);
                return (
                  <div key={i} className="flex-1 flex flex-col items-center gap-1 group relative">
                    {/* Tooltip */}
                    <div className="opacity-0 group-hover:opacity-100 transition-opacity absolute -top-8 bg-slate-800 text-white text-[10px] font-mono px-2 py-0.5 rounded shadow pointer-events-none whitespace-nowrap z-10 border border-slate-700">
                      {bin.count} houses ({Math.round((bin.count / RAW_HOUSES.length) * 100)}%)
                    </div>
                    <span className="text-[10px] font-mono text-slate-400">{bin.count}</span>
                    <div
                      style={{ height: `${Math.max(8, heightPct)}%` }}
                      className="w-full bg-gradient-to-t from-blue-600 to-cyan-400 rounded-t transition-all group-hover:brightness-110"
                    />
                    <span className="text-[9px] text-slate-400 font-mono text-center truncate w-full mt-1" title={bin.label}>
                      {bin.label}
                    </span>
                  </div>
                );
              })}
            </div>

            {/* Observations Card */}
            <div className="bg-slate-800/50 p-3 rounded-lg border border-slate-800 text-xs space-y-1">
              <div className="font-semibold text-blue-300 flex items-center gap-1.5">
                <Info className="w-3.5 h-3.5" />
                <span>Observation & Analysis:</span>
              </div>
              <p className="text-slate-300 text-[11px] leading-relaxed">
                The price distribution is moderately <strong>right-skewed</strong> (positive skew). Over 65% of homes are concentrated between <strong>$300,000 and $750,000</strong>, while a long right tail extends towards luxury multi-million dollar properties in Bellevue/Medina.
              </p>
            </div>
          </div>
        )}

        {/* Plot 2: Living Area vs Price Scatter Plot */}
        {(activeChart === 'all' || activeChart === 'reg') && (
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 shadow-sm space-y-4">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <div className="flex items-center gap-2">
                <TrendingUp className="w-4 h-4 text-emerald-400" />
                <h3 className="text-white font-semibold text-sm">2. Living Area (sqft) vs Price ($)</h3>
              </div>
              <span className="text-[11px] text-slate-400 font-mono">sns.regplot(r ≈ 0.70)</span>
            </div>

            {/* SVG Scatter Plot */}
            <div className="h-56 relative border-l border-b border-slate-700 bg-slate-950/40 rounded-sm p-2 overflow-hidden">
              {/* Regression Trend Line */}
              <svg className="absolute inset-0 w-full h-full pointer-events-none">
                <line
                  x1="5%"
                  y1="90%"
                  x2="95%"
                  y2="15%"
                  stroke="#ef4444"
                  strokeWidth="2.5"
                  strokeDasharray="4 2"
                />
              </svg>

              {/* Data points */}
              {scatterPoints.map((pt, i) => (
                <div
                  key={i}
                  style={{ left: `${Math.min(96, Math.max(4, pt.x))}%`, top: `${Math.min(94, Math.max(6, pt.y))}%` }}
                  className="absolute w-2.5 h-2.5 -ml-1 -mt-1 rounded-full bg-emerald-400/80 hover:bg-white hover:scale-150 border border-emerald-950 transition-all cursor-pointer group"
                  title={`${pt.sqft} sqft → $${pt.price.toLocaleString()}`}
                >
                  <div className="opacity-0 group-hover:opacity-100 transition-opacity absolute -top-8 -left-12 bg-slate-900 text-white text-[10px] font-mono px-2 py-0.5 rounded shadow pointer-events-none whitespace-nowrap z-20 border border-slate-700">
                    {pt.sqft} sqft: ${pt.price.toLocaleString()}
                  </div>
                </div>
              ))}

              <div className="absolute top-2 right-2 bg-slate-900/90 border border-slate-700 text-[10px] text-slate-300 px-2 py-1 rounded font-mono">
                Red Line: Linear OLS Trend
              </div>
            </div>

            {/* Observations Card */}
            <div className="bg-slate-800/50 p-3 rounded-lg border border-slate-800 text-xs space-y-1">
              <div className="font-semibold text-emerald-300 flex items-center gap-1.5">
                <Info className="w-3.5 h-3.5" />
                <span>Observation & Analysis:</span>
              </div>
              <p className="text-slate-300 text-[11px] leading-relaxed">
                There is a <strong>strong positive linear correlation ($r = 0.70$)</strong>. Each additional 100 square feet of finished living space increases the baseline property valuation by approximately <strong>$17,845</strong>.
              </p>
            </div>
          </div>
        )}

        {/* Plot 3: Feature Correlation Heatmap */}
        {(activeChart === 'all' || activeChart === 'heatmap') && (
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 shadow-sm space-y-4">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <div className="flex items-center gap-2">
                <Grid className="w-4 h-4 text-indigo-400" />
                <h3 className="text-white font-semibold text-sm">3. Feature Correlation Heatmap</h3>
              </div>
              <span className="text-[11px] text-slate-400 font-mono">sns.heatmap(df.corr())</span>
            </div>

            {/* Heatmap Table */}
            <div className="overflow-x-auto">
              <table className="w-full text-center text-xs border-collapse">
                <thead>
                  <tr>
                    <th className="p-1.5 text-left text-slate-400 font-medium text-[11px]">Feature</th>
                    {corrFeatures.map((f) => (
                      <th key={f.id} className="p-1.5 text-slate-300 font-mono text-[10px] truncate max-w-[60px]" title={f.label}>
                        {f.label.split(' ')[0]}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {corrFeatures.map((rowF, rowIdx) => (
                    <tr key={rowF.id} className="border-t border-slate-800">
                      <td className="p-1.5 text-left text-slate-300 font-medium text-[11px] whitespace-nowrap">
                        {rowF.label}
                      </td>
                      {corrMatrix[rowIdx].map((val, colIdx) => (
                        <td key={colIdx} className="p-1">
                          <div className={`py-1.5 rounded text-[11px] font-mono transition-transform hover:scale-105 ${getCorrColor(val)}`}>
                            {val.toFixed(2)}
                          </div>
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Observations Card */}
            <div className="bg-slate-800/50 p-3 rounded-lg border border-slate-800 text-xs space-y-1">
              <div className="font-semibold text-indigo-300 flex items-center gap-1.5">
                <Info className="w-3.5 h-3.5" />
                <span>Observation & Analysis:</span>
              </div>
              <p className="text-slate-300 text-[11px] leading-relaxed">
                <strong>sqft_living (0.70)</strong> and <strong>grade (0.67)</strong> are the two highest predictors of house price. In contrast, <strong>bedrooms (0.31)</strong> shows lower standalone correlation because without square footage context, adding rooms alone does not equal luxury.
              </p>
            </div>
          </div>
        )}

        {/* Plot 4: Actual vs Predicted Prices */}
        {(activeChart === 'all' || activeChart === 'actual_pred') && (
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 shadow-sm space-y-4">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <div className="flex items-center gap-2">
                <Activity className="w-4 h-4 text-cyan-400" />
                <h3 className="text-white font-semibold text-sm">4. Actual vs. Predicted Prices (Test Set)</h3>
              </div>
              <span className="text-[11px] text-slate-400 font-mono">Holdout Test Set (20%)</span>
            </div>

            {/* Side-by-side Scatter & Ideal Line */}
            <div className="h-56 relative border-l border-b border-slate-700 bg-slate-950/40 rounded-sm p-2 overflow-hidden">
              <svg className="absolute inset-0 w-full h-full pointer-events-none">
                {/* 45 degree perfect prediction line */}
                <line
                  x1="5%"
                  y1="95%"
                  x2="95%"
                  y2="5%"
                  stroke="#38bdf8"
                  strokeWidth="2"
                  strokeDasharray="3 3"
                />
              </svg>

              {/* Points */}
              {testSamples.map((s, idx) => {
                const xPct = ((s.actual - 200000) / (1500000 - 200000)) * 90 + 5;
                const yPct = 95 - (((s.pred - 200000) / (1500000 - 200000)) * 90);
                return (
                  <div
                    key={idx}
                    style={{ left: `${Math.min(95, Math.max(5, xPct))}%`, top: `${Math.min(95, Math.max(5, yPct))}%` }}
                    className="absolute w-2.5 h-2.5 -ml-1 -mt-1 rounded-full bg-cyan-400 hover:bg-white hover:scale-150 border border-slate-900 transition-all cursor-pointer group"
                    title={`Actual: $${s.actual.toLocaleString()} | Predicted: $${s.pred.toLocaleString()}`}
                  >
                    <div className="opacity-0 group-hover:opacity-100 transition-opacity absolute -top-8 -left-16 bg-slate-900 text-white text-[10px] font-mono px-2 py-0.5 rounded shadow pointer-events-none whitespace-nowrap z-20 border border-slate-700">
                      Act: ${s.actual.toLocaleString()} | Pred: ${s.pred.toLocaleString()}
                    </div>
                  </div>
                );
              })}

              <div className="absolute top-2 left-2 bg-slate-900/90 border border-slate-700 text-[10px] text-slate-300 px-2 py-1 rounded font-mono">
                Dashed Line: Perfect 1:1 Prediction ($y = x$)
              </div>
            </div>

            {/* Observations Card */}
            <div className="bg-slate-800/50 p-3 rounded-lg border border-slate-800 text-xs space-y-1">
              <div className="font-semibold text-cyan-300 flex items-center gap-1.5">
                <CheckCircle className="w-3.5 h-3.5 text-cyan-400" />
                <span>Observation & Validation:</span>
              </div>
              <p className="text-slate-300 text-[11px] leading-relaxed">
                Test set points cluster tightly along the diagonal identity line ($R^2 = 0.7285$). The average prediction variance remains steady across price brackets with minimal heteroscedasticity.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
